namespace Data
{
	struct Music {
		String Title;
		String Album;
		String Genre;
		String Artist;
		String Albumartist;
		String Path;
		Int64 Duration;
		UInt32 Year;
		UInt32 Bitrate;
		UInt32 Track;
	};
}