// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Player
{
    [default_interface]
    runtimeclass About : Microsoft.UI.Xaml.Controls.Page
    {
        About();
    }
}
