// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Player
{
    [default_interface]
    runtimeclass MusicInfo : Microsoft.UI.Xaml.Controls.Page
    {
        MusicInfo();
    }
}
