import "Library.idl";
namespace Player
{
    [bindable]
    [default_interface]
    runtimeclass PlayerViewModel: Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        PlayerViewModel();
        Double Volume;
        UInt32 Index;
        Double Position;
        Double Duration;
        Data.Library Library;
        static String DoubleToString(Double volume);
        static String DurationToString(Double duration);
    }
}
