import "Library.idl";
namespace Player
{
    [bindable]
    [default_interface]
    runtimeclass PlayerViewModel: Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        PlayerViewModel();
        String AppTitle;
        Double Volume;
        Data.Library Library;
        UInt32 Index;
        String Title;
        String Album;
        String Artist;
        Double Position;
        Double Duration;
        Microsoft.UI.Xaml.Media.ImageSource Image;
        static String DoubleToString(Double volume);
        static String DurationToString(Double duration);
    }
}
