import "Data.idl";
import "InfoViewModel.idl";
import "RootPage.idl";
namespace Player
{
    [default_interface]
    runtimeclass FolderView : Microsoft.UI.Xaml.Controls.Page
    {
        FolderView();
        Windows.Foundation.Collections.IObservableVector<InfoViewModel> MusicList{get; };
        Windows.Foundation.Collections.IObservableVector<String> FolderList{get; };
        String CalculateTrueFolderCount(UInt32 value);
        static String TransformBitrate(UInt32 value);
        static String TransformDuration(Int64 value);
        static String DecisionTitle(String title, String path);
        static String DecisionArtist(String artist, String albumartist);
    }
}
