import "PlayerViewModel.idl";
import "InfoViewModel.idl";

namespace Player
{
    [default_interface]
    runtimeclass NowPlaying : Microsoft.UI.Xaml.Controls.Page
    {
        NowPlaying();
        PlayerViewModel PlayerViewModel{ get; };
        Windows.Foundation.Collections.IObservableVector<InfoViewModel> MusicList{ get; };
    }
}
