namespace Player
{
    [default_interface]
    runtimeclass EditLibrary : Microsoft.UI.Xaml.Controls.Page
    {
        EditLibrary();
        EditLibrary(String name, String protocol, String path, String icon);
    }
}
