import "Data.idl";

namespace Player
{
    [default_interface]
    runtimeclass MusicInfoModel
    {
        MusicInfoModel();
        MusicInfoModel(ref const Player.Data.MusicInfo info);
        Player.Data.MusicInfo Info{get; set; };
    }
}