import "PlayerViewModel.idl";
import "Data.idl";
namespace Player
{
    [default_interface]
    runtimeclass RootPage : Microsoft.UI.Xaml.Controls.Page
    {
        RootPage();
        String AppTitleText;
        Windows.Media.Playback.MediaPlayer Player{ get; };
        Windows.Media.Playback.MediaPlaybackList List{ get; };
        Microsoft.UI.Xaml.Controls.Frame GetRootFrame();
        Microsoft.UI.Xaml.Controls.Grid GetAppTitleBar();
        PlayerViewModel PlayerMainViewModel{ get; };
        static Windows.Foundation.Collections.IObservableVector<Data.Library> Libraries{get; };
        static Windows.Foundation.Collections.IObservableVector<Data.MusicInfo> Music{get; };
    }
}
