// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace Player
{
    [default_interface]
    runtimeclass RootPage : Microsoft.UI.Xaml.Controls.Page
    {
        RootPage();
        String AppTitleText;
        Microsoft.UI.Xaml.Controls.Frame GetRootFrame();
    }
}
