import "PlayerViewModel.idl";
namespace Player
{
    [default_interface]
    runtimeclass RootPage : Microsoft.UI.Xaml.Controls.Page
    {
        RootPage();
        String AppTitleText;
        PlayerViewModel PlayerMainViewModel{ get; };
        Windows.Media.Playback.MediaPlayer Player{ get; };
        Windows.Media.Playback.MediaPlaybackList List{ get; };
        Microsoft.UI.Xaml.Controls.Frame GetRootFrame();
        Microsoft.UI.Xaml.Controls.Grid GetAppTitleBar();
    }
}
